name: Auto-Increment Patch Version

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Create new Git tag
        run: |
          VERSION=${{ steps.version.outputs.version }}
          git tag $VERSION
          git push origin $VERSION

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=${{ steps.version.outputs.version }}
          gh release create $VERSION target/*.jar --title "Release $VERSION" --notes "Release notes for version $VERSION"

